name: "Smart Irrigation Controller"
description: "Advanced irrigation control system for hydroponic and soil-based growing"
version: "1.1.0"
slug: smart_irrigation
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ingress: true
panel_icon: mdi:sprinkler-variant
panel_title: "Irrigation Controller"
panel_admin: false
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?